lavalink:
  plugins:
    - dependency: com.github.topi314.lavasrc:lavasrc-plugin:4.8.1
      snapshot: false
    - dependency: dev.lavalink.youtube:youtube-plugin:1.16.0
      snapshot: false
    - dependency: com.github.topi314.lavasearch:lavasearch-plugin:1.0.0
      snapshot: false
    # - dependency: com.dunctebot:skybot-lavalink-plugin:1.7.0
    #   repository: https://maven.lavalink.dev/releases
    #   snapshot: false
    # - dependency: com.github.devoxin:lavadspx-plugin:0.0.5
    #   repository: https://jitpack.io
    #   snapshot: false
    # - dependency: net.esmbot:lava-xm-plugin:0.2.8
    #   repository: https://repo.projectlounge.pw/maven/releases
    #   snapshot: false
    # - dependency: com.github.topi314.lavalyrics:lavalyrics-plugin:1.1.0
    #   snapshot: false
    # - dependency: dev.schlaubi.lyrics:lavalink:2.6.1
    #   snapshot: false
  server:
    password: "youshallnotpass"
    sources:
      # The default Youtube source is now deprecated and won't receive further updates. Please use https://github.com/lavalink-devs/youtube-source#plugin instead.
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: false
      vimeo: true
      nico: true
      http: true # warning: keeping HTTP enabled without a proxy configured could expose your server's IP address.
      local: false
    filters: # All filters are enabled by default
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true
    nonAllocatingFrameBuffer: false # Setting to true reduces the number of allocations made by each player at the expense of frame rebuilding (e.g. non-instantaneous volume changes)
    bufferDurationMs: 400 # The duration of the NAS buffer. Higher values fare better against longer GC pauses. Duration <= 0 to disable JDA-NAS. Minimum of 40ms, lower values may introduce pauses.
    frameBufferDurationMs: 5000 # How many milliseconds of audio to keep buffered
    opusEncodingQuality: 10 # Opus encoder quality. Valid values range from 0 to 10, where 10 is best quality but is the most expensive on the CPU.
    resamplingQuality: LOW # Quality of resampling operations. Valid values are LOW, MEDIUM and HIGH, where HIGH uses the most CPU.
    trackStuckThresholdMs: 10000 # The threshold for how long a track can be stuck. A track is stuck if does not return any audio data.
    useSeekGhosting: true # Seek ghosting is the effect where whilst a seek is in progress, the audio buffer is read from until empty, or until seek is ready.
    youtubePlaylistLoadLimit: 6 # Number of pages at 100 each
    playerUpdateInterval: 5 # How frequently to send player updates to clients, in seconds
    youtubeSearchEnabled: true
    soundcloudSearchEnabled: true
    gc-warnings: true
#    ratelimit:
#      ipBlocks: [ "1.0.0.0/8", "..." ] # list of ip blocks
#      excludedIps: [ "...", "..." ] # ips which should be explicit excluded from usage by lavalink
#      strategy: "RotateOnBan" # RotateOnBan | LoadBalance | NanoSwitch | RotatingNanoSwitch
#      searchTriggersFail: true # Whether a search 429 should trigger marking the ip as failing
#      retryLimit: -1 # -1 = use default lavaplayer value | 0 = infinity | >0 = retry will happen this numbers times
#    youtubeConfig: # Required for avoiding all age restrictions by YouTube, some restricted videos still can be played without.
#      email: "" # Email of Google account
#      password: "" # Password of Google account
#    httpConfig: # Useful for blocking bad-actors from ip-grabbing your music node and attacking it, this way only the http proxy will be attacked
#      proxyHost: "localhost" # Hostname of the proxy, (ip or domain)
#      proxyPort: 3128 # Proxy port, 3128 is the default for squidProxy
#      proxyUser: "" # Optional user for basic authentication fields, leave blank if you don't use basic auth
#    proxyPassword: "" # Password for basic authentication

plugins:
    lavasrc:
        lyrics-sources:
            applemusic: false
            deezer: false
            lrcLib: false
            spotify: false
            tidal: false
            yandexmusic: false
            youtube: true
        providers:
            - ytsearch:"%ISRC%"
            - ytsearch:"%QUERY%"
        sources:
            applemusic: false
            bandcamp: false
            deezer: false
            flowerytts: false
            jiosaavn: false
            lrcLib: false
            nico: false
            qobuz: false
            spotify: false
            tidal: false
            twitch: false
            vimeo: false
            yandexmusic: false
            youtube: true
        youtube:
            countryCode: US
            language: en    
    youtube:
        remoteCipher:
          url: "https://cipher.kikkia.dev/"
          userAgent: "longkang_cleaner" # Optional
        allowDirectPlaylistIds: true
        allowDirectVideoIds: true
        allowSearch: true
        clientOptions:
            ANDROID_VR:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            IOS:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            MUSIC:
                playback: false
                playlistLoading: false
                searching: true
                videoLoading: false
            MWEB:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            TV:
                playback: true
                playlistLoading: false
                searching: false
                videoLoading: false
            TVHTML5EMBEDDED:
                playback: true
                playlistLoading: false
                searching: true
                videoLoading: true
            WEB:
                playback: true
                playlistLoading: true
                searching: true
                videoLoading: true
            WEBEMBEDDED:
                playback: true
                playlistLoading: false
                searching: false
                videoLoading: true
        clients:
            - TV
            - TVHTML5EMBEDDED
            - WEB
            - MWEB
            - WEBEMBEDDED
            - MUSIC
            - ANDROID_VR
            - IOS
        enabled: true
        oauth:
            enabled: true
            refreshToken: 
            skipInitialization: false

logging:
    file:
        max-history: 30
        max-size: 1GB
        path: ./logs/
    level:
        com.github.topi314.lavasrc: INFO
        com.github.topi314.lavasrc.LavaSrcTools: DEBUG
        com.sedmelluq.discord.lavaplayer.source.youtube.YoutubePersistentHttpStream: "OFF"
        com.sedmelluq.discord.lavaplayer.tools.ExceptionTools: "OFF"
        com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream: "OFF"
        dev.lavalink.youtube: INFO
        dev.lavalink.youtube.YoutubeAudioSourceManager: "OFF"
        dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO
        lavalink: INFO
        lavalink.server.io.SocketContext: "OFF"
        root: INFO
    logback:
        rollingpolicy:
            max-file-size: 1GB
            max-history: 30
    request:
        enabled: true
        includeClientInfo: true
        includeHeaders: false
        includePayload: true
        includeQueryString: true
        maxPayloadLength: 1000

metrics:
    prometheus:
        enabled: true
        endpoint: /metrics

sentry:
    dsn: ""
    environment: ""

server:
    address: 0.0.0.0
    http2:
        enabled: true
    port: 2333

spring:
    main:
        banner-mode: log
    profiles:
        active: production